#!/bin/sh

exec postgraphile \
	--append-plugins @graphile-contrib/pg-simplify-inflector,@graphile-contrib/pg-many-to-many,postgraphile-plugin-connection-filter \
	--dynamic-json \
	--enhance-graphiql \
	--no-setof-functions-contain-nulls \
	--disable-query-log \
	--simple-collections both \
	--connection postgres://postgres@localhost/postgres \
	"$@"
